apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{.Values.app.name}}
  name: {{.Values.app.name}}
spec:
  ports:
  - name: {{.Values.app.name}}
    port: {{.Values.app.port}}
    protocol: TCP
    targetPort: {{.Values.app.port}}
  selector:
    app: {{.Values.app.name}}
  type: {{.Values.app.type}}
status:
  loadBalancer: {}
