apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
        name: myrole1
        namespace: default
rules:
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["list", "watch", "get"]
